### ISSUE TITLE
Issues with plugin installation on Windows10

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#271]
**was no notifications of missings Scala plugin**

installed a plugin from `test` branch on Windows 10 clean, turned into A+ project, did not restart 

```
java.lang.NoClassDefFoundError: org/jetbrains/plugins/scala/project/ScalaLibraryType$Kind$
	at fi.aalto.cs.apluscourses.intellij.model.CommonLibraryProvider.createLibrary(CommonLibraryProvider.java:39)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at fi.aalto.cs.apluscourses.intellij.model.CommonLibraryProvider.getComponentIfExists(CommonLibraryProvider.java:27)
	at fi.aalto.cs.apluscourses.intellij.model.IntelliJCourse.getComponentIfExists(IntelliJCourse.java:82)
	at fi.aalto.cs.apluscourses.model.ComponentSource.getComponent(ComponentSource.java:16)
	at fi.aalto.cs.apluscourses.model.ComponentSource.getComponents(ComponentSource.java:38)
	at fi.aalto.cs.apluscourses.model.ComponentInstallerImpl$Installation.waitForDependencies(ComponentInstallerImpl.java:151)
	at fi.aalto.cs.apluscourses.model.ComponentInstallerImpl$Installation.doIt(ComponentInstallerImpl.java:93)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.scala.project.ScalaLibraryType$Kind$ PluginClassLoader[fi.aalto.cs.intellij-plugin, 0.1.0] com.intellij.ide.plugins.cl.PluginClassLoader@42185095
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 10 more
```
restarted, things started to crash and burn... :fire:

```
java.lang.NoClassDefFoundError: org/jetbrains/plugins/scala/project/ScalaLibraryType$Kind$
	at fi.aalto.cs.apluscourses.intellij.model.CommonLibraryProvider.createLibrary(CommonLibraryProvider.java:39)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at fi.aalto.cs.apluscourses.intellij.model.CommonLibraryProvider.getComponentIfExists(CommonLibraryProvider.java:27)
	at fi.aalto.cs.apluscourses.intellij.model.IntelliJCourse.getComponentIfExists(IntelliJCourse.java:82)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:533)
	at fi.aalto.cs.apluscourses.model.Component.areDependenciesLoaded(Component.java:127)
	at fi.aalto.cs.apluscourses.model.Component.validate(Component.java:148)
	at fi.aalto.cs.apluscourses.model.Course.validate(Course.java:445)
	at fi.aalto.cs.apluscourses.model.Course.resolve(Course.java:437)
	at fi.aalto.cs.apluscourses.intellij.model.IntelliJModelFactory.createCourse(IntelliJModelFactory.java:51)
	at fi.aalto.cs.apluscourses.model.Course.fromConfigurationData(Course.java:145)
	at fi.aalto.cs.apluscourses.model.Course.fromUrl(Course.java:169)
	at fi.aalto.cs.apluscourses.intellij.actions.CourseProjectAction.lambda$new$0(CourseProjectAction.java:94)
	at fi.aalto.cs.apluscourses.intellij.actions.CourseProjectAction.tryGetCourse(CourseProjectAction.java:188)
	at fi.aalto.cs.apluscourses.intellij.actions.CourseProjectAction.actionPerformed(CourseProjectAction.java:124)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6650)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.scala.project.ScalaLibraryType$Kind$ PluginClassLoader[fi.aalto.cs.intellij-plugin, 0.1.0] com.intellij.ide.plugins.cl.PluginClassLoader@887858f
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 75 more
```

**Comment by superseacat** [comment]
I suspect there might be some change in the way Scala plugin ID is

**Comment by OlliKiljunen** [comment]
Was Scala plugin installed?

**Comment by OlliKiljunen** [comment]
Is this the same bug as #224 ?

**Comment by superseacat** [comment]
feels more of https://github.com/Aalto-LeTech/intellij-plugin/issues/181 type of issue, I'm thinking of moving the "required plugin check" higher in the 
```java
@Override
 public void runActivity(@NotNull Project project) {...
```

**Comment by superseacat** [comment]
https://github.com/Aalto-LeTech/intellij-plugin/pull/268#issuecomment-666200593

**Comment by superseacat** [comment]
not relevant anymore
