### ISSUE TITLE
IDE settings import issue on Windows

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#312]
Under some specific circumstances, the IDE settings import (done as part of the _Turn Project Into A+ Project_ action) causes an `IOException`. It most likely has to do with file permissions instead of network errors.

Some details:
  + The error does not occur when creating a new project from the launcher view.
  + The error does occur when creating a new project while an existing project is open (even if the new project replaces the existing project in the window).
  + Changing settings (for an example changing the theme to dark) before using the action prevents the error.

@OlliKiljunen ran into the following exception, which seems related:
```
Couldn't backup current config or delete current config directoryjava.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.base/java.io.FileInputStream.readBytes(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:257)
	at com.intellij.openapi.util.io.FileUtilRt.copy(FileUtilRt.java:1052)
	at com.intellij.openapi.util.io.FileUtil.copy(FileUtil.java:431)
	at com.intellij.openapi.util.io.FileUtil.performCopy(FileUtil.java:396)
	at com.intellij.openapi.util.io.FileUtil.copy(FileUtil.java:384)
	at com.intellij.openapi.util.io.FileUtil.copyDir(FileUtil.java:502)
	at com.intellij.openapi.util.io.FileUtil.copyDir(FileUtil.java:482)
	at com.intellij.openapi.util.io.FileUtil.copyDir(FileUtil.java:463)
	at com.intellij.openapi.application.ConfigImportHelper.backupCurrentConfigToTempAndDelete(ConfigImportHelper.java:238)
	at com.intellij.openapi.application.ConfigImportHelper.importConfigsTo(ConfigImportHelper.java:134)
	at com.intellij.idea.StartupUtil.lambda$startApp$5(StartupUtil.java:277)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:417)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90
```

**Comment by superseacat** [comment]
https://apluslms.slack.com/archives/CQ92SAHNY/p1597233892477100

**Comment by OlliKiljunen** [comment]
This happened at the similar situation (on Windows) when turning project into A+ project.

Stack here doesn't contain our code but it seems the error was thrown when some other error was tried to be logged, so the root cause is possibly (or even probably) the same error as in this issue.

```
java.lang.Throwable: Project Project(name=untitled27, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\Olli\IdeaProjects\untitled27) already disposed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:200)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:187)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:305)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:244)
	at com.intellij.openapi.command.WriteCommandAction.lambda$execute$0(WriteCommandAction.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:475)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:126)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:497)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by superseacat** [comment]
till Tue 18.8 evening

**Comment by OlliKiljunen** [comment]
This could not be reproduced. Issue closed for now. Let's see if the problem still occurs on Juha's machine with the next release.
