### ISSUE TITLE
issue when trying to submit s2 assignment

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#440]
```java
org.json.JSONException: JSONObject["exercise_info"] is not a JSONObject.
	at org.json.JSONObject.getJSONObject(JSONObject.java:770)
	at fi.aalto.cs.apluscourses.model.SubmissionInfo.fromJsonObject(SubmissionInfo.java:35)
```
when trying to submit... 

what's different here:
* Kalevala: https://plus.cs.aalto.fi/api/v2/exercises/30069/
* GoodStuff: https://plus.cs.aalto.fi/api/v2/exercises/26041/

**Comment by superseacat** [comment]
issue was related to a) course being "closed", b) @oseppala being able to submit as he's a super-duper-user in A+

**WORKS**
