### ISSUE TITLE
FileNotFoundException that Juha found

### ISSUE THREAD

**Issue by stellatsv** [Aalto-LeTech/intellij-plugin#729]
Created a new project, immediately turned it into an A+ project (for O1 2020), got an error.

java.io.FileNotFoundException: D:\o1\.idea\workspace.xml (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:652)
at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246)
at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
at fi.aalto.cs.apluscourses.utils.DomUtil.parse(DomUtil.java:146)
at fi.aalto.cs.apluscourses.intellij.model.SettingsImporter.createCustomWorkspaceXml(SettingsImporter.java:171)
at fi.aalto.cs.apluscourses.intellij.model.SettingsImporter.importProjectSettings(SettingsImporter.java:100)
at fi.aalto.cs.apluscourses.intellij.actions.CourseProjectAction.tryImportProjectSettings(CourseProjectAction.java:348)
at fi.aalto.cs.apluscourses.intellij.actions.CourseProjectAction.lambda$actionPerformed$3(CourseProjectAction.java:213)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Taikelenn** [comment]
Could not reproduce, probably not caused by the plugin itself
